### ISSUE TITLE
Dockerised fatfree redirects broken

### ISSUE THREAD

**Issue by MarkBFamFour** [bcosca/fatfree#1275]
I have a Fat Free Framework 3.8 application running in a docker setup via php-fpm and nginx containers and then exposing the nginx port on the docker host. All is fine **except** when I use a redirect. It seems like F3 is trying to use the container `hostname` to dynamically build the redirect URL and it is screwing up the webapp because it is using the container `hostname`, not the host's where the user is browsing to.

**For example:**

`http://192.168.1.2/reports`
should redirect to:
`http://192.168.1.2/login`
if no user login is detected before rendering.
192.168.1.2 is the host docker server IP

Instead it redirects to:
`http://9de4ghb543/login`
which fails as the user's web client has no knowledge of that hostname

Can I hard-code or set via a hive variable the *hostname* anywhere? I see there is a `HOST` system variable but it is currently Read-only?

Would using a nginx proxy to the docker host work better maybe if so how can I determine or setup the hostname during the docker-compose?

**docker-compose.yml**

```
version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '/var/www/my-app:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '4000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '/var/www/my-app:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
```

**nginx.conf**

```
server {
    listen 80 default;

    client_max_body_size 58M;

    access_log /var/log/nginx/access.log;

    #/application/src is my f3 root
    root /application/src/public_html;
    index index.php;

    # try to serve file directly, fallback to index.php
    location / {
        try_files $uri /index.php$is_args$args;
    }

    if (!-e $request_filename) {
        rewrite ^.*$ /index.php last;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "error_log=/var/log/nginx/errors.log";
        fastcgi_param APP_ENV "PRODUCTION";
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;
    }
}
```
